FROM ubuntu:16.04
MAINTAINER Irina Goltsman <irina-goltsman@yandex.ru>

ENV HOME /root

RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential git cmake
RUN pip3 install --upgrade pip

# RUN git clone https://github.com/dmylzenova/celebrity_faces.git

# RUN pip3 install -r requirements.txt
RUN pip3 install Cython==0.28.2
RUN pip3 install Flask==1.0.2
RUN pip3 install Flask-Uploads==0.2.1
RUN pip3 install ipython==6.3.1
RUN pip3 install opencv-python==3.4.0.12
RUN pip3 install tensorflow==1.8.0
RUN pip3 install gevent==1.3.0 

# CMD celebrity_faces/viewer/run.py --port=2018 --host='0.0.0.0'


